name: Build and Test
on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "Dockerfile"
  push:
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "Dockerfile"

jobs:
  lint-testing:
    name: Code Formatting Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r serpenttracker/requirements.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
  django-tests:
    name: Django Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U 'pip<20'
          pip install -r serpenttracker/requirements.txt
      - name: Bring Up Compose Stack
        run: docker-compose up -d
      - name: Running Migrations
        run: docker-compose exec -T web python manage.py migrate --noinput
      - name: Report Coverage to Coveralls
        working-directory: ${{ github.workspace }}/serpenttracker
        env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          ls -lah
          coveralls 