name: Build and Test
on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "Dockerfile"
  push:
    paths-ignore:
      - "README.md"
      - "Makefile"
      - "Dockerfile"

jobs:
  lint-testing:
    name: Code Formatting Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r serpenttracker/requirements.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
  django-tests:
    name: Django Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bring Up Compose Stack
        run: docker-compose up -d
      - name: Running Migrations
        run: docker-compose exec -T web python manage.py migrate --noinput
      - name: Checking Docker
        run: docker ps
      - name: Test with django tests
        run: |
          docker-compose exec -T web python manage.py test
      - name: Report Coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: docker-compose exec -T web coveralls 